config/routes.rb
Rails.application.routes.draw do
  resource :sessions, :only => [:new, :create, :destroy]

  get 'signup' => 'cats#new'
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  resources :cats

  #pages :
  root 'pages#home'
  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  #attr_accessor :password
  has_many :microposts, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: {}, uniqueness: {}
  validates :email, presence: {}, uniqueness: {}, :format => {with: email_regex}
  validates :password, presence: {}, confirmation: { case_sensitive: true }
  validates :password_confirmation, presence: {}
  before_save :encrypt_password

  def has_password?(password_soumis)
    password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    cat = find_by_email(email)
    return nil  if cat.nil?
    return cat if cat.has_password?(submitted_password)
  end

  def admin?
    :admin
  end

  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :cat

  validates :content, presence: {}, length: {maximum: 140}
  validates :user_id, presence: {}

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :nom, :email

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :nom, :presence => true,
            :length   => { :maximum => 50 }

  validates :email, :presence => true,
            :format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user

  private

  def set_current_user
    if session[:cat_id]
      @current_user = Cat.find(session[:cat_id])
    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :authenticate, :only => [:index, :edit, :update, :destroy]
  before_action :correct_user, :only => [:edit, :update]
  before_action :admin_user, :only => :destroy
  include SessionsHelper, ApplicationHelper

  def new
    @titre = "Inscription"
    @cat = Cat.new
  end

  def show
    @cat = Cat.find(params[:id])
    @titre = @cat.name
  end

  def create
    @cat = Cat.new cat_params
    if @cat.save
      flash[:success] = "Bienvenue dans l'Application Exemple!"
      session[:cat_id] = @cat.id
      redirect_to @cat
    else
      @titre = "Inscription"
      render 'new'
    end
  end

  def edit
    @titre = "Edition du profil"
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      flash[:success] = "Profil actualisé."
      redirect_to @cat
    else
      @titre = "Edition du profil"
      render 'edit'
    end
  end

  def index
    @titre = "Tous les utilisateurs"
    @cats = Cat.page(params[:page]).per(10)
  end

  def destroy
    Cat.find(params[:id]).destroy
    flash[:success] = "Utilisateur supprimé."
    redirect_to cats_path
  end

  private

  def admin_user
    redirect_to(root_path) unless @current_user.admin?
  end

  def authenticate
    deny_access unless signed_in?
  end

  def correct_user
    @cat = Cat.find(params[:id])
    redirect_to(root_path , :notice => "Vous n'avez pas les droits de modifications sur cette utilisateur.") unless current_user?(@cat)
  end

  def cat_params
    params.require(:cat).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titre = "Accueil"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "À Propos"
  end

  def help
    @titre = "Aide"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
    @titre = "S'identifier"
  end

  def create
    user = Cat.authenticate(params[:sessions][:email],
                            params[:sessions][:password])
    if user.nil?
      flash.now[:error] = "Combinaison Email/Mot de passe invalide."
      @titre = "S'identifier"
      render 'new'
    else
      session[:cat_id] = user.id
      flash[:info] = "Vous êtes maintenant connecté"
      redirect_back_or user
    end
  end

  def destroy
    flash[:info] = "Vous êtes maintenant déconnecté"
    session[:cat_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

  def signed_in?
    session[:cat_id]
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Merci de vous identifier pour rejoindre cette page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def current_user?(user)
    user == @current_user
  end

  private

  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_return_to
    session[:return_to] = nil
  end

end

app/views/cats/_cat.html.erb
<li>
  <%= link_to cat.name, cat %>
  <% if signed_in?%>
    <% if @current_user.admin? %>
      <span class="tabulation">
        | <%= link_to "supprimer", cat, method: :delete, data: {confirm: "Etes-vous certain ?" } %>
      </span>
    <% end %>
  <% end %>
</li>

app/views/cats/edit.html.erb
<h1>Edition du profil :</h1>

<%= form_for(@cat) do |f| %>

  <div class="field">
    <%= f.label :name, "Nom" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "eMail" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Mot de passe" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation mot de passe" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" , class: "round" %>
  </div>
<% end %>

app/views/cats/index.html.erb
<h1>Tous les utilisateurs</h1>

<ul class="users">
  <%= render @cats %>
</ul>

<%= paginate @cats %>

app/views/cats/new.html.erb
<h1>Inscription</h1>

<%= form_for(@cat) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Inscription" %>
  </div>
<% end %>

app/views/cats/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= @cat.name %>
      </h1>
      <h4>
        <%= @cat.email %>
      </h4>
      <p>
        <% if signed_in? %>
          <% if current_user?(@cat) %>
            <%= link_to "Modifier mon profile", edit_cat_path(@current_user) %>
          <% end %>
        <% end %>
      </p>
    </td>
    <td>
      <% unless @cat.microposts.empty? %>
        <table class="microposts" summary="Micro-messages de l'utilisateur">
          <%= render @microposts %>
        </table>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @cat.name %><br/>
      <strong>URL</strong>  <%= link_to cat_path(@cat), @cat %>
    </td>
  </tr>
</table>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("large.png", :alt => "Application Exemple", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <li>
        <% if signed_in? %>
          <%= link_to "Profil", cats_path + "/#{@current_user.id}" %>
        <% end %>
      </li>
      <li><%= link_to "Liste utilisateurs", cats_path %></li>
      <li><%= link_to "Aide", help_path %></li>
      <li>
        <% if signed_in? %>
          <%= link_to "Déconnexion", signout_path, :methode => :delete %>
        <% else %>
          <%= link_to "Connexion", signin_path %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titre %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posté il y a <%= time_ago_in_words(micropost.created_at) %>.
    </span>
  </td>
</tr>

app/views/pages/about.html.erb
<h1>À Propos de nous</h1>
<p>
  <a href="http://railstutorial.org/">Le Tutoriel Ruby on Rails</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. Ceci
  est l'Application Exemple du tutoriel.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial à propos de l'Application Exemple à
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette Application Exemple, voyez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<h1>Simple App</h1>
<p>
  Ceci est la page d'accueil de l'Application Exemple du
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.
</p>
<%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @cat.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@cat.errors.count, "erreur") %>
      ont empêché d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
      <% @cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<%= @user.nom %>, <%= @user.email %>